---
#roles/homebrew/tasks/main.yml
- homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items: homebrew.taps

- homebrew: update_homebrew=yes

- homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state|default('latest') }}"
    install_options: "{{ item.install_options|default() }}"
  with_items: homebrew.packages
